# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Team4B1G_VG

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformCli@0
  inputs:
    targetAzureSubscription: '$(subscription)'
    targetStorageAccountName: 'terraformstate9827349'
    script: | 
      set -e -x

      cd aks_advnet_rbac

      # Init terraform using the defined storage account 

      env

      terraform init \
        -backend-config="storage_account_name=$(TFSTATE_STORAGE)"
        
      # Generate a terraform plan file
      terraform plan \
        -input=false \
        -var="ARM_CLIENT_ID=$(ARM_CLIENT_ID)" \
        -var="ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)" \
        -out=plan.tfplan
        
      # Apply the terraform plan
      terraform apply plan.tfplan 

